# Generated by Django 3.0.1 on 2020-01-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200124_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sheets_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
