# Generated by Django 3.0.1 on 2020-01-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheets_id', models.CharField(default='', max_length=15)),
                ('current_equity', models.IntegerField()),
                ('net_equity_deposit', models.IntegerField()),
                ('estimated_annual_incom', models.IntegerField()),
            ],
        ),
    ]
