# Generated by Django 3.0.1 on 2020-01-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200126_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('performance', models.FloatField()),
                ('sp500', models.FloatField()),
            ],
        ),
    ]
