# Generated by Django 3.0.1 on 2020-01-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_partnershipdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipdata',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
