# Generated by Django 3.0.1 on 2020-01-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200126_0837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
