# Generated by Django 3.0.1 on 2020-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_userdata_percentage_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='daily_gain',
            field=models.FloatField(default=0.0),
        ),
    ]
