# Generated by Django 3.0.1 on 2020-06-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userdata_daily_gain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheets_id', models.CharField(max_length=15, unique=True)),
                ('transaction_amount', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
