# Generated by Django 3.0.1 on 2020-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='sheets_id',
            field=models.CharField(max_length=15),
        ),
    ]
