# Generated by Django 3.0.1 on 2020-07-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200620_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=40, unique=True)),
                ('position_size', models.FloatField()),
                ('category', models.CharField(max_length=60)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('change_pct', models.FloatField()),
                ('change', models.FloatField()),
                ('todays_gain', models.FloatField()),
                ('overall_gain', models.FloatField()),
                ('overall_pct_gain', models.FloatField()),
                ('div_per_share', models.FloatField()),
                ('incom_pct', models.FloatField()),
                ('dividend', models.FloatField()),
                ('volume', models.FloatField()),
                ('volume_avg', models.FloatField()),
            ],
        ),
    ]
