# Generated by Django 3.0.1 on 2020-07-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_holdings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdings',
            old_name='incom_pct',
            new_name='income_pct',
        ),
    ]
